# Generated by Django 5.1 on 2024-09-01 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Resource', models.CharField(max_length=200, verbose_name='Ресурс')),
                ('Price', models.IntegerField(verbose_name='Цена')),
                ('Efficiency', models.IntegerField(verbose_name='Производство в мин')),
                ('Is_created', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Ресурсы',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, verbose_name='Имя')),
                ('Level', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Уровень')),
                ('Experience', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('Time', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Время изготовления')),
                ('Level', models.IntegerField()),
                ('is_active', models.BooleanField()),
                ('Product', models.ManyToManyField(related_name='product', to='main.resources')),
                ('used_resource', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.resources')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.users')),
            ],
        ),
        migrations.CreateModel(
            name='Users_resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sum', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Количество')),
                ('Is_active', models.BooleanField()),
                ('Resource', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.resources')),
                ('User', models.ForeignKey(default='null', on_delete=django.db.models.deletion.DO_NOTHING, to='main.users')),
            ],
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Level', models.IntegerField(verbose_name='Уровень')),
                ('Price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Цена')),
                ('Created_resource', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.resources', verbose_name='Производимый ресурс')),
                ('User', models.ForeignKey(default='null', on_delete=django.db.models.deletion.DO_NOTHING, to='main.users')),
            ],
        ),
    ]
