# Generated by Django 5.1.1 on 2024-09-16 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fabric',
            options={'verbose_name_plural': 'Фабрики'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='users_resources',
            options={'verbose_name_plural': 'Ресурсы пользователя'},
        ),
        migrations.AlterModelOptions(
            name='workers',
            options={'verbose_name_plural': 'Рабочие'},
        ),
        migrations.RenameField(
            model_name='fabric',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='fabric',
            old_name='used_resource',
            new_name='Used_resource',
        ),
    ]
