# Generated by Django 5.1.1 on 2024-09-16 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_fabric_options_alter_users_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fabric',
            name='Level',
        ),
        migrations.CreateModel(
            name='Users_fabric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Level', models.IntegerField()),
                ('Fabric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.fabric')),
                ('User', models.ForeignKey(default='null', on_delete=django.db.models.deletion.DO_NOTHING, to='main.users')),
            ],
            options={
                'verbose_name_plural': 'Фабрики пользователя',
            },
        ),
    ]
