# Generated by Django 5.1.1 on 2024-09-16 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_fabric_level_users_fabric'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fabric',
            name='User',
        ),
        migrations.RemoveField(
            model_name='fabric',
            name='is_active',
        ),
        migrations.AddField(
            model_name='users_fabric',
            name='is_active',
            field=models.BooleanField(default='False'),
        ),
        migrations.RemoveField(
            model_name='fabric',
            name='Product',
        ),
        migrations.AddField(
            model_name='fabric',
            name='Product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product', to='main.resources'),
            preserve_default=False,
        ),
    ]
